In [1]:
import torch
import torch.nn.functional as F
import torch.nn as nn
x = torch.randn(5, 5)

In [2]:
print(x)

tensor([[ 0.3368, -1.7569, -0.6021,  0.2159,  2.5563],
        [-0.3027, -0.4771,  0.2575, -0.2526, -0.8680],
        [ 1.4113,  2.8128, -1.8577,  1.1255, -0.7856],
        [-1.4850,  2.5400, -0.5721, -0.2935,  0.2038],
        [-1.2397, -0.2223,  1.0395,  0.0317, -0.8771]])


In [4]:
target = torch.tensor([0, 2, 3, 1, 4]) # 标签
one_hot = F.one_hot(target).float() # 对标签进行one_hot编码

In [5]:
print(one_hot)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.]])


In [6]:
softmax = torch.exp(x)/torch.sum(torch.exp(x), dim = 1).reshape(-1, 1)

In [7]:
print(softmax)

tensor([[0.0862, 0.0106, 0.0337, 0.0764, 0.7931],
        [0.1919, 0.1612, 0.3360, 0.2018, 0.1091],
        [0.1677, 0.6812, 0.0064, 0.1260, 0.0186],
        [0.0147, 0.8211, 0.0365, 0.0483, 0.0794],
        [0.0539, 0.1492, 0.5270, 0.1924, 0.0775]])


In [8]:
logsoftmax = torch.log(softmax)
print(logsoftmax)

tensor([[-2.4513, -4.5450, -3.3902, -2.5722, -0.2318],
        [-1.6507, -1.8251, -1.0905, -1.6005, -2.2159],
        [-1.7854, -0.3839, -5.0544, -2.0711, -3.9822],
        [-4.2221, -0.1971, -3.3092, -3.0306, -2.5333],
        [-2.9198, -1.9024, -0.6406, -1.6484, -2.5572]])


In [9]:
print(target.shape[0])

5


In [17]:
nllloss = -torch.sum(one_hot*logsoftmax)/target.shape[0]
print(nllloss)

tensor(1.6734)


In [11]:
logsoftmax = F.log_softmax(x, dim = 1)
print(logsoftmax)

tensor([[-2.4513, -4.5450, -3.3902, -2.5722, -0.2318],
        [-1.6507, -1.8251, -1.0905, -1.6005, -2.2159],
        [-1.7854, -0.3839, -5.0544, -2.0711, -3.9822],
        [-4.2221, -0.1971, -3.3092, -3.0306, -2.5333],
        [-2.9198, -1.9024, -0.6406, -1.6484, -2.5572]])


In [12]:
nllloss = F.nll_loss(logsoftmax, target)
print(nllloss)

tensor(1.6734)


In [13]:
cross_entropy = F.cross_entropy(x, target)
print(cross_entropy)

tensor(1.6734)


In [15]:
loss = torch.nn.CrossEntropyLoss()
c = loss(x, target)
print(c)

tensor(1.6734)
